routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'App\Http\Controllers\HomeController@index');

Route::get('/dashboard', function () {
    return view('admin.layouts.adminhome');
})->middleware(['auth'])->name('dashboard');

Route::resource('users', Admin\UserController::class);
Route::resource('food', Admin\FoodController::class);


Route::post('/changeStatus',[Admin\UserController::class, 'changeStatus']);
require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Session;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $user = User::where('id', $id)->first();
      
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $validated = $request->validate([
        'name' => 'required',
        'email' => 'required|email|unique:users,email,'.$id,
        'password' => 'required|min:6',
        'password_confirmation' => 'required|same:password|min:6'
    ]);

      $userUpdate = User::findOrFail($id)->update([
        'name'        => $request->name,
        'email'       => $request->email,
        'password'    => $request->password,
      ]);

      return redirect()->back()->with('message', 'Data updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $user = User::findOrFail($id)->delete();

      return redirect()->back()->with('message', 'Data deleted successfully.');
    }

    public function changeStatus(Request $request )
    {
      $user = User::findOrFail($request->id);
      if ($request->status == "true") {
          $user->update([
            'status' => 1
          ]);
    } else {
          $user->update([
            'status'  => 0
          ]);
    }
    Session::flash('message', 'Status changed successfully.');
        return response()->json([
          'message'  =>  'Status changed successfully.'
        ]);
    }
}

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.adminhome')
@section('title', 'Edit Users')

@section('content')
@if(session()->has('message'))
    <div class="alert alert-success">
        {{ session()->get('message') }}
    </div>
@endif
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10 my-5">
  <div class="row">
    <div class="col-md-10">
    <h3>Edit User</h3>
    </div>
    <div class="col-md-2">
      <a href="/users" class="btn btn-success">Back</a>
    </div>
  </div>
  <div class="form-group">
    <form class="" action="{{ route('users.update', $user->id) }}" method="POST">
      @csrf
      <input type="hidden" name="_method" value="PUT">
      <div class="form-group my-3">
        <label for="name">Name</label>
        <input type="text" name="name" class="form-control @error('title', 'post') is-invalid @enderror" value="{{$user->name}}">
        @error('name')
         <div class="alert alert-danger">{{ $message }}</div>
         @enderror
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input type="text" name="email" class="form-control" value="{{$user->email}}">
        @error('email')
         <div class="alert alert-danger">{{ $message }}</div>
         @enderror
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="text" name="password" class="form-control" value="">
        @error('password')
         <div class="alert alert-danger">{{ $message }}</div>
         @enderror
      </div>
      <div class="form-group">
        <label for="password_confirmation">Confirm Password</label>
        <input type="text" name="password_confirmation" class="form-control" value="">
        @error('password_confirmation')
         <div class="alert alert-danger">{{ $message }}</div>
         @enderror
      </div>
      <button type="submit"  class="btn btn-success">Update</button>
    </form>
  </div>
  </div>
  <div class="col-md-1"></div>
</div>


@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.adminhome')
@section('title', 'Users')
@section('content')
@if(session()->has('message'))
    <div class="alert alert-success" id ="message">
        {{ session()->get('message') }}
    </div>
@endif
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <h2 class="my-3">Users</h2>
    <table class="table table-striped table-dark" id="datatable">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Member Since</th>
      <th scope="col">Status</th>
      <th scope="col" class="text-center">Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach($users as $user)
    @if(Auth::user()->id != $user->id)
    <tr>
      <th scope="row">{{$user->id}}</th>
      <td>{{$user->name}}</td>
      <td>{{$user->email}}</td>
      <td>{{$user->created_at->format('j F, Y')}}</td>
      <td>{{$user->status == 0 ? 'Active' : 'Inactive'}} </td>
      <td class="text-center">
      <ul class="list-inline m-0">
            <li class="list-inline-item">
              <input type="checkbox"  data-toggle="toggle" data-style="slow" data-size="xs" onChange="getStatus(this)" id="getStatus" value="{{$user->id}}" {{$user->status == 1 ? 'checked' : ''}} >
            </li>
            <li class="list-inline-item">
                 <a class="btn btn-success btn-sm rounded-0 button-height" href="{{ route('users.edit', ['user' => $user->id]) }}" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
            </li>
            <li class="list-inline-item">
              <form action="{{ URL::route('users.destroy', ['user' => $user->id]) }}" method="POST">
               @csrf
               {{ method_field("DELETE") }}
                  <button class="btn btn-danger btn-sm rounded-0 button-height delete-confirm" id="delete" type="submit" data-toggle="tooltip" onsubmit="confirmDelete(this.)" data-placement="top" title="Delete"><i class="fa fa-trash"></i></button>
            </li>
        </ul>
      </td>
    </tr>
    @endif
    @endforeach

  </tbody>
</table>
    </div>
    <div class="col-md-1"></div>
</div>

@endsection

@section('script')
<script>
    $(document).ready( function () {
    $('#datatable').DataTable();
} );

$('[data-toggle="tooltip"]').tooltip();

  function getStatus(status) {
     var status= $('#getStatus').prop('checked');
     var id = $('#getStatus').val();
     $.ajax({
      url: "{{url('changeStatus')}}",
      method : "POST",
      data : {id, status, _token:"{{csrf_token()}}"},
      success: function(response) {
        if(response) {
                $("#message").html(response.message);
                window.location.reload();
          }
      }
     });

   }

$('.delete-confirm').click(function(event) {
     var form =  $(this).closest("form");

     event.preventDefault();
     swal({
         title: `Are you sure you want to delete this record?`,
         text: "If you delete this, it will be gone forever.",
         icon: "warning",
         buttons: true,
         dangerMode: true,
     })
     .then((willDelete) => {
       if (willDelete) {
         form.submit();
       }
     });
 });
</script>

@endsection