routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'App\Http\Controllers\HomeController@index');

Route::get('/dashboard', function () {
    return view('admin.layouts.adminhome');
})->middleware(['auth'])->name('dashboard');

Route::resource('users', Admin\UserController::class);
Route::resource('food', Admin\FoodController::class);


Route::post('/changeStatus',[Admin\UserController::class, 'changeStatus']);
require __DIR__.'/auth.php';

app/Models/Food.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Food extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'price', 'description', 'photo'];
}

app/Http/Controllers/Admin/FoodController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Food;
use Session;
use Illuminate\Support\Facades\Validator;

class FoodController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $foods = Food::all();

        return view('admin.food.index', compact('foods'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.food.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
      'title'       => 'required',
      'price'       => 'required',
      'description' => 'required',
      ]);

      if ($request->hasFile('image')) {
          $request->validate([
          'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
        ]);
        $path = 'public/images';
        $image = $request->file('image');
        $imageName = $image->getClientOriginalName();
        $path = $request->file('image')->storeAs($path, $imageName);
      }

      $food = Food::create([
        'title'        => $request->title,
        'price'        => $request->price,
        'description'  => $request->description,
        'photo'        => $imageName,
      ]);
      return redirect()->back()->with('message', 'Food saved successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        echo "<pre>"; print_r('show'); die;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $food = Food::findOrFail($id);

        return response()->json( $food);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $validator = Validator::make($request->all(),[
        'title'       => 'required',
        'price'       => 'required',
        'description' => 'required',
        ]);

      if ($validator->fails()) {
          return redirect()->back()
                           ->withErrors($validator)
                           ->withInput();
        }

      if ($request->has('image')) {
          $request->validate([
          'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
        ]);

        $path = 'public/images';
        $image = $request->file('image');
        $imageName = time().$image->getClientOriginalName();
        $path = $request->file('image')->storeAs($path, $imageName);
        $food = Food::findOrFail($request->id)->update([
            'photo'        => $imageName,
        ]);
      }

        $food = Food::findOrFail($request->id)->update([
          'title'        => $request->title,
          'price'        => $request->price,
          'description'  => $request->description,
        ]);

          return redirect()->back()->with('message', 'Food updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Food::find($id)->delete();

      return redirect()->back()->with('message', 'Data deleted successfully');
    }
}

resources/views/admin/food/create.blade.php
@extends('admin.layouts.adminhome')

@section('title', 'Create Food')

@section('content')
@if(session()->has('message'))
    <div class="alert alert-success">
        {{ session()->get('message') }}
    </div>
@endif
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="row">
      <div class="col-md-2 my-3">
        <h3>Create Food</h3>
      </div>
      <div class="col-md-8">
        <a href="/food" class="btn btn-success my-3 pull-right">Back</a>
      </div>
      <div class="col-md-2">

      </div>
    </div>
    <div class="row">
      <form class="" action="{{ route('food.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label for="title">Title</label>
          <input type="text" name="title" value="{{ old('title') }}" placeholder="Enter Title" autocomplete="off" class="form-control @error('title') is-invalid @enderror">
          @error('title')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="price">Price</label>
          <input type="number" name="price" value="{{ old('price') }}" placeholder="Enter Price" autocomplete="off" class="form-control @error('price') is-invalid @enderror">
          @error('price')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea name="description" value="{{ old('description') }}" placeholder="Enter Description" class="form-control @error('description') is-invalid @enderror"  rows="4">
          </textarea>
          @error('description')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="photo">Photo</label>
          <input type="file" name="image" class="form-control @error('photo') is-invalid @enderror">
          @error('image')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
          <input type="submit" name="submit" value="Save" class="btn btn-success">
      </form>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>
@endsection

resources/views/admin/food/edit-food-modal.blade.php
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Edit Food</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="foodData">
      <form class="" action="{{ route('food.update', ['food' => $food->id])}}" method="post" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="form-group">
          <label for="price">Price</label>
          <input type="text" name="price" value=" {{ old ('price') }}" class="form-control" id="price">
          @error('price')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="title">Title</label>
          <input type="text" name="title" value="{{ old ('title') }}" class="form-control" id="title">
          @error('title')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea name="description" rows="8" cols="40" class="form-control" id="description">{{ old ('description') }}</textarea>
          @error('description')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="image">Image</label>
          <input type="file" name="image" value="" class="form-control">
          @error('image')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        </div>
      </div>
      <div class="modal-footer">
        <input type="hidden" name="id" value="" id='id'>
        <button type="button" id="close-btn" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/admin/food/index.blade.php
@extends('admin.layouts.adminhome')

@section('title' , 'Food')

@section('content')
  @if(session()->has('message'))
      <div class="alert alert-success">
          {{ session()->get('message') }}
      </div>
  @endif

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-9">
      <div class="row">
        <div class="col-md-6">
          <h2 class="my-3">Food</h2>
        </div>
        <div class="col-md-6">
          <a href="{{ route('food.create') }}" class="btn btn-success my-3 pull-right">Create Food</a>
        </div>
      </div>
    <table class="table table-striped table-dark" id="datatable">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Price</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Image</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach($foods as $food)
    <tr>
      <th scope="row">{{$food->id}}</th>
      <td>{{$food->price}}</td>
      <td>{{$food->title}}</td>
      <td>{{ Str::limit($food->description, 50) }}</td>
      <td> <img src="{{ asset('/storage/images/' . $food->photo) }}" height="250" width="200"/> </td>
      <td class="text-center">
      <ul class="list-inline m-0">
            <li class="list-inline-item">
                 <a class="btn btn-success btn-sm rounded-0 button-height editFood"  href="javascript:void(0)" id="editFood" data-toggle="modal" data-target="#exampleModalLong" dataId= "{{ $food->id }}"><i class="fa fa-edit"></i></a>
            </li>
            <li class="list-inline-item">
              <form action="{{ URL::route('food.destroy', ['food' => $food->id]) }}" method="POST">
               @csrf
               {{ method_field("DELETE") }}
                  <button class="btn btn-danger btn-sm rounded-0 button-height delete-confirm" id="delete" type="submit" data-toggle="tooltip" onsubmit="confirmDelete(this.)" data-placement="top" title="Delete"><i class="fa fa-trash"></i></button>
                </form>
            </li>
        </ul>
      </td>
    </tr>

    @endforeach

  </tbody>
  </table>
    </div>
    <div class="col-md-2"> </div>
  </div>
  @include('admin.food.edit-food-modal')

  @endsection

  @section('script')
  <script>
      $(document).ready( function () {
      $('#datatable').DataTable();
  } );

  $('.delete-confirm').click(function(event) {
       var form =  $(this).closest("form");

       event.preventDefault();
       swal({
           title: `Are you sure you want to delete this record?`,
           text: "If you delete this, it will be gone forever.",
           icon: "warning",
           buttons: true,
           dangerMode: true,
       })
       .then((willDelete) => {
         if (willDelete) {
           form.submit();
         }
       });
   });

$('.editFood').on('click', function() {
   foodId = $(this).attr('dataId');
   url = '/food' + '/' + foodId + '/edit'
  $.ajax({
    type : 'GET',
    url: url,
    success: function (food) {
      $('#id').val(food.id);
      $('#price').val(food.price);
      $('#title').val(food.title);
      $('#description').val(food.description);
    },
  });

});

@if (count($errors) > 0)
    $('#exampleModalLong').modal('show');
@endif
</script>
@endsection